server:
  port: 8086
spring:
  application:
    name: order-processing-service

  datasource:
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:"  # Required Config Server
  cloud:
    config:
      uri: http://localHost:8888
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092  # Fallback value
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-group
      properties:
        spring.json.trusted.packages: '*'  # Allow deserialization of custom objects
        listener:
          missing-topics-fatal: false  # Avoid failure when a topic doesn't exist

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

